name: Publish Docker image

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:

  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - uses: actions/checkout@v4

    - name: Log in to Docker
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: .
        build-args: |
          CUDA_VERSION=12.2
        file: ./vastai/julia.Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/gpu-runners-julia:vastai-cuda12.2
        cache-to: type=gha
        cache-from: type=gha,mode=max
