name: Publish Docker image

on:
  release:
    types: [published]

jobs:

  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        build-args: |
          CUDA_VERSION=12.2
        file: ./vastai/julia.Dockerfile
        push: true
        tags: ${{ github.repository_owner }}/gpu-runners-julia:vastai-cuda12.2
